package main

import (
	"bytes"
	"go/format"
	"html/template"
	"io/ioutil"
	"log"
)

var path = "./plugin/plugin.go"

var templateCode = `// Code generated by gen_embed_var.go; DO NOT EDIT.
package main

import "fmt"

var V int

func F() { fmt.Printf("Hello, number %d\n", V) }
`

func main() {
	tmpl, err := template.New("gen").Parse(templateCode)
	if err != nil {
		log.Fatal("template Parse:", err)
	}

	var out bytes.Buffer
	err = tmpl.Execute(&out, nil)
	if err != nil {
		log.Fatal("template Execute:", err)
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal("format:", err)
	}

	if err := ioutil.WriteFile(path, formatted, 0644); err != nil {
		log.Fatal("writeFile:", err)
	}

}
